# Generated by Django 3.1.7 on 2021-03-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='list_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
