# Generated by Django 3.1.7 on 2021-03-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0002_table_list_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_id', models.TextField()),
                ('correct_answer', models.TextField()),
                ('valuation', models.TextField()),
            ],
        ),
    ]
