# Generated by Django 3.1.7 on 2021-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0003_finaltab'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltab',
            name='user_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
