# Generated by Django 3.1.7 on 2021-03-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0004_finaltab_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltab',
            name='paragraph',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
