# Generated by Django 3.1.7 on 2021-03-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0005_finaltab_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='experience',
            field=models.CharField(choices=[('Beg', 'Beginner'), ('Int', 'Intermediate'), ('Adv', 'Advanced')], default=123, max_length=300),
            preserve_default=False,
        ),
    ]
