# Generated by Django 3.1.7 on 2021-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0006_account_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltab',
            name='exp_number',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
