# Generated by Django 3.0.3 on 2021-04-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0007_finaltab_exp_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='list_id',
            new_name='exp_set',
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
