# Generated by Django 3.0.3 on 2021-04-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0008_auto_20210425_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='clause',
        ),
        migrations.RemoveField(
            model_name='table',
            name='clause_id',
        ),
        migrations.RemoveField(
            model_name='table',
            name='concept',
        ),
    ]
