# Generated by Django 3.0.3 on 2021-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0009_auto_20210425_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='list_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
