# Generated by Django 3.0.3 on 2021-04-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0011_finaltab2_table2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField()),
                ('sex', models.TextField()),
                ('language_num', models.TextField()),
                ('school', models.TextField()),
                ('grammar', models.TextField()),
                ('lexic', models.TextField()),
                ('language_other', models.TextField()),
                ('education', models.TextField()),
                ('language_education', models.TextField()),
                ('contact', models.TextField()),
                ('group', models.TextField()),
            ],
        ),
    ]
