# Generated by Django 3.0.3 on 2021-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0012_userq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.TextField()),
                ('user_number', models.TextField()),
            ],
        ),
    ]
