# Generated by Django 3.0.3 on 2021-05-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0013_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='user_try',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
