# Generated by Django 3.0.3 on 2021-05-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0014_orden_user_try'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='experience',
        ),
    ]
