# Generated by Django 3.0.3 on 2021-05-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0015_remove_account_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userq',
            name='language_child',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
