# Generated by Django 3.0.3 on 2021-05-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0016_userq_language_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='userq',
            name='email',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
