# Generated by Django 3.0.3 on 2021-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexp', '0017_userq_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finaltab',
            old_name='exp_number',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='finaltab',
            old_name='paragraph',
            new_name='answer_rate',
        ),
        migrations.RenameField(
            model_name='finaltab',
            old_name='sentence_id',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='finaltab',
            old_name='valuation',
            new_name='exp_set',
        ),
        migrations.RenameField(
            model_name='finaltab2',
            old_name='exp_number',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='finaltab2',
            old_name='paragraph',
            new_name='answer_rate',
        ),
        migrations.RenameField(
            model_name='finaltab2',
            old_name='sentence_id',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='finaltab2',
            old_name='valuation',
            new_name='exp_set',
        ),
        migrations.AddField(
            model_name='finaltab',
            name='feedback_rate',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaltab',
            name='n_id',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaltab',
            name='n_try',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaltab',
            name='paragraph_rate',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaltab2',
            name='feedback_rate',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaltab2',
            name='n_id',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaltab2',
            name='n_try',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaltab2',
            name='paragraph_rate',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
